# docker-compose.yml (Versión Final Automatizada)

version: '3.8'

services:
  # Servicio de la aplicación Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        user: arnold_onzalez # Reemplaza con tu usuario local para permisos
        uid: 1000 # Reemplaza con el UID de tu usuario (ejecuta `id -u`)
    container_name: ecom-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    # El 'command' se ejecuta después de que el contenedor se construye y levanta.
    # Automatiza todos los pasos de configuración de Laravel.
    command: >
      sh -c "
        composer install &&
        php artisan key:generate &&
        php artisan config:clear &&
        php artisan route:clear &&
        php artisan cache:clear &&
        php artisan migrate:fresh --seed --force &&
        php artisan l5-swagger:generate &&
        php-fpm
      "
    networks:
      - ecom_network

  # Servidor Web Nginx
  nginx:
    image: nginx:1.21-alpine
    container_name: ecom-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # Nginx solo arrancará después de que la app y la db estén listas
      - app 
      - db
    networks:
      - ecom_network

  # Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ecom-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecom_network

  # Servidor de Caché Redis
  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    restart: unless-stopped
    ports:
      - "63790:6379"
    networks:
      - ecom_network

networks:
  ecom_network:
    driver: bridge

volumes:
  db_data:
    driver: local
